version: '3.3'
services:
  db:
    image: mongo:7.0-rc-jammy
    restart: always 
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: nest-pokemon
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db
    networks:
      - node-network
volumes:
  mongo:
networks:
  node-network:
    driver: bridge